[package]
name = "ruststeg"
version = "0.1.6"
edition = "2024"
authors = ["ScalierBullet63"]

license = "GPL-3.0-only"
description = "A working progress Rust steganography CLI tool for images, audios and videos!"
readme = "README.md"
repository = "https://github.com/ScalierBullet63/ruststeg"

keywords = ["steganography", "cli", "security"]
categories = ["command-line-utilities"]

[dependencies]
argon2 = "0.6.0"
bitflags = "2.13.1"
chacha20poly1305 = "0.11.0"
clap = { version = "4.6.1", features = ["derive"] }
image = "0.25.10"
rand = "0.10.2"
rpassword = "7.5.4"
yn = "0.1.1"
zeroize = "1.9.0"

# The profile that 'dist' will build with
[profile.dist]
inherits = "release"
lto = "thin"
